[build]
  publish = "BrandOtpOfficial/frontend"

# Redirect API calls to your backend
[[redirects]]
  from = "/api/*"
  to = "https://brandotp-project1.onrender.com/api/:splat"
  status = 200
  force = true

# Handle client-side routing for all HTML pages
[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/signup"
  to = "/signup.html"
  status = 200

[[redirects]]
  from = "/buy-number"
  to = "/buy_number.html"
  status = 200

[[redirects]]
  from = "/add-money"
  to = "/add_money.html"
  status = 200

[[redirects]]
  from = "/auth"
  to = "/auth.html"
  status = 200

[[redirects]]
  from = "/history"
  to = "/history.html"
  status = 200

[[redirects]]
  from = "/wallet"
  to = "/wallet.html"
  status = 200

[[redirects]]
  from = "/payment-success"
  to = "/payment-success.html"
  status = 200

# Default fallback to index
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
